<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
  <!ELEMENT books (book*)>
  <!ELEMENT book (title,author,edition_year*)>
  <!ATTLIST book publisher CDATA #IMPLIED
                 isbn      ID    #IMPLIED>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT edition_year (#PCDATA)>
]>
<books>
  <book publisher="Planeta" isbn="C386379-001">
    <title>Five Hours with Mario</title>
    <author>Miguel Delibes</author>
    <edition_year>1967</edition_year>
  </book>
  <book>
    <title>One Hundred Years of Solitude</title>
    <author>Gabriel García Márquez</author>
  </book>
</books>
